### ISSUE TITLE
404 GET https://storage.googleapis.com/storage/v1/b/my_demo_project?projection=noAcl: Not Found

### ISSUE THREAD

**Issue by rushaligupta** [priyankavergadia/Django-Dialogflow-GoogleVisionAPI#1]
Hi,

i'm getting the following error while running localhost server:

404 GET https://storage.googleapis.com/storage/v1/b/my_demo_project?projection=noAcl: Not Found

Request Method: | GET
-- | --
http://127.0.0.1:8000/
2.1.5
NotFound
404 GET https://storage.googleapis.com/storage/v1/b/my_demo_project?projection=noAcl: Not Found
C:\Users\My Pc\Downloads\Django-Dialogflow-GoogleVisionAPI-master\Django-Dialogflow-GoogleVisionAPI-master\venv\lib\site-packages\google\cloud\_http.py in api_request, line 393
C:\Users\My Pc\Downloads\Django-Dialogflow-GoogleVisionAPI-master\Django-Dialogflow-GoogleVisionAPI-master\venv\Scripts\python.exe
3.5.2
['C:\\Users\\My '  'Pc\\Downloads\\Django-Dialogflow-GoogleVisionAPI-master\\Django-Dialogflow-GoogleVisionAPI-master',  'C:\\Users\\My '  'Pc\\Downloads\\Django-Dialogflow-GoogleVisionAPI-master\\Django-Dialogflow-GoogleVisionAPI-master\\venv\\Scripts\\python35.zip',  'C:\\Python-3.5\\Lib',  'C:\\Python-3.5\\DLLs',  'C:\\Users\\My Pc\\Desktop\\project_env\\Scripts',  'C:\\Users\\My '  'Pc\\Downloads\\Django-Dialogflow-GoogleVisionAPI-master\\Django-Dialogflow-GoogleVisionAPI-master\\venv',  'C:\\Users\\My '  'Pc\\Downloads\\Django-Dialogflow-GoogleVisionAPI-master\\Django-Dialogflow-GoogleVisionAPI-master\\venv\\lib\\site-packages']
Thu, 14 Nov 2019 10:39:17 +0000

I've made both my buckets public. i'm not able to figure out why is this error coming. 
Please help me through this. its a bit urgent issue. Thanks .

**Comment by mdfarooq0815** [comment]
@rushaligupta Can you please tell me what was your fix as you closed the issue and I am getting the same error. Thanks

**Comment by rushaligupta** [comment]
Hi, really sorry, but I don't remember the exact issue and resolution to
this.
But yes, I think there was some issue with the credentials. Using a
different API call(bypassing some network configurations) worked I believe.
But that might not be the recommended approach.

Thanks,
Rushali
